### PR TITLE
Solve #3 - setup webpack for development

### PR DESCRIPTION
**Pull request by mazipan**
+ Add readme for developer
+ Add webpack config for development

### CODE REVIEW

**Comment by eezhal92** [comment]
Mau nanya, hasil bundle-nya ga di gunain di index.html?

**Comment by mazipan** [comment]
Dipakai kok.

**Comment by mazipan** [comment]
Udah resolved ya conflict nya @tyohan

**Comment by tyohan** [comment]
thanks @mazipan

**Pull request merged**
